### ISSUE TITLE
Errors in [make -j$(nproc) STATIC=1]

### ISSUE THREAD

**Issue by wwt02** [alfalfa/daala_tools#1]
Hello, I met a problem. When I input a instruction [make -j$(nproc) STATIC=1] in ubuntu20, the screen shows some errors that follow below
[src/y4m_input.c:32:10: fatal error: ogg/os_types.h: No such file or directory
   32 | #include <ogg/os_types.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
src/vidinput.c:33:10: fatal error: ogg/os_types.h: No such file or directory
   33 | #include <ogg/os_types.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:68: src/vidinput.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:68: src/y4m_input.o] Error 1
src/y4m2png.c:57:10: fatal error: ogg/os_types.h: No such file or directory
   57 | #include <ogg/os_types.h>]. 
In the meanwhile, I don’t know how to solve it. I hope that I can get your help.

**Comment by kwantam** [comment]
Without looking more deeply, it appears that either you don't have the ogg headers installed, or the ogg headers have been moved to a different location. I would bet the first---maybe try `sudo apt-get install libogg-dev`?

**Comment by wwt02** [comment]
Thanks, kwantam . I solve this problem.
